// Generated by CoffeeScript 1.7.1
(function() {
  var ErrorResponse, MimeType, RootPath, fs, http, path, port, serveFile, serveGzFile, server, zlib;

  fs = require('fs');

  path = require('path');

  http = require('http');

  zlib = require('zlib');

  MimeType = {
    html: 'text/html',
    js: 'text/javascript',
    css: 'text/css',
    csv: 'text/csv'
  };

  ErrorResponse = {
    EACCES: [403, 'Forbidden'],
    ENOENT: [404, 'Not Found'],
    DEFAULT: [500, 'Internal server error']
  };

  RootPath = 'public';

  serveFile = function(res, url, mime) {
    var stream;
    stream = fs.createReadStream(url);
    stream.on('error', function(err) {
      var errRes;
      errRes = ErrorResponse[err.code] || ErrorResponse.DEFAULT;
      res.writeHead(errRes[0], {
        'Content-Type': 'text/plain'
      });
      res.end("" + errRes[0] + " " + errRes[1]);
    });
    res.writeHead(200, {
      'Content-Type': mime
    });
    stream.pipe(res);
  };

  serveGzFile = function(res, url, gzipSupported) {
    var headers, mime, stream, urlGz;
    mime = MimeType[path.extname(url).substr(1)] || 'text/plain';
    url = RootPath + url;
    urlGz = url + '.gz';
    headers = {
      'Content-Type': mime
    };
    if (gzipSupported) {
      stream = fs.createReadStream(urlGz);
      stream.on('error', function(err) {
        serveFile(res, url, mime);
      });
      headers['Content-Encoding'] = 'gzip';
      res.writeHead(200, headers);
      stream.pipe(res);
    } else {
      fs.readFile(urlGz, function(err, data) {
        if (err != null) {
          serveFile(res, url, mime);
        } else {
          zlib.gunzip(data, function(err, result) {
            var errRes;
            if (err != null) {
              errRes = ErrorResponse.DEFAULT;
              res.writeHead(errRes[0], {
                'Content-Type': 'text/plain'
              });
              return res.end("" + errRes[0] + " " + errRes[1]);
            } else {
              res.writeHead(200, headers);
              return res.end(result);
            }
          });
        }
      });
    }
  };

  server = http.createServer(function(request, res) {
    var enc, url;
    url = request.url;
    if (url === '/') {
      url = '/index.html';
    }
    enc = request.headers['accept-encoding'];
    serveGzFile(res, url, (enc != null) && enc.indexOf('gzip') !== -1);
  });

  port = Number(process.env.PORT || 8888);

  server.listen(port);

}).call(this);
